### ISSUE TITLE
mt_experience.sp(135) : error 180: function return type differs from prototype. expected 'int', but got 'void'

### ISSUE THREAD

**Issue by BRU7U5** [TouchMe-Inc/l4d2_mix_team#10]
https://github.com/TouchMe-Inc/l4d2_mix_team/blob/e1f2201459de91b26d9c20fa63ab70c14ae2431a/addons/sourcemod/scripting/mt_experience.sp#LL135C36-L135C36

**Comment by TouchMe-Inc** [comment]
SteamWorks version taken from this repository (README)
-> [My SteamWorks](https://github.com/hexa-core-eu/SteamWorks/blob/main/Pawn/includes/SteamWorks.inc#L295)
