### ISSUE TITLE
[BUG] mt_experience.smx GetVoteEndMessage missing

### ISSUE THREAD

**Issue by PencilMario** [TouchMe-Inc/l4d2_mix_team#12]
L 05/29/2023 - 08:47:28: [SM] Exception reported: Failed to get the function id of GetVoteEndMessage
L 05/29/2023 - 08:47:28: [SM] Blaming: mix_team.smx
L 05/29/2023 - 08:47:28: [SM] Call stack trace:
L 05/29/2023 - 08:47:28: [SM]   [0] SetFailState
L 05/29/2023 - 08:47:28: [SM]   [1] Line 878, e:\GithubKu\L4D2-Competitive-Rework\addons\sourcemod\scripting\mix_team.sp::HandlerVote
L 05/29/2023 - 08:47:28: [SM]   [3] Call_Finish
L 05/29/2023 - 08:47:28: [SM]   [4] Line 840, nativevotes.sp::DoAction
L 05/29/2023 - 08:47:28: [SM]   [5] Line 878, nativevotes.sp::OnVoteResults
L 05/29/2023 - 08:47:28: [SM]   [6] Line 1134, nativevotes.sp::EndVoting
L 05/29/2023 - 08:47:28: [SM]   [7] Line 1309, nativevotes.sp::DisplayTimer

**Comment by TouchMe-Inc** [comment]
Check README (Require > [NativeVotesRework](https://github.com/TouchMe-Inc/l4d2_nativevotes_rework))
I made this plugin to fix a bug with voting results (6 - for, 2 against = fail)
