### ISSUE TITLE
[BUG] Unable to get player details

### ISSUE THREAD

**Issue by PencilMario** [TouchMe-Inc/l4d2_mix_team#13]
In the old version I wrote before, when using steamwork to query information, if the person has not been queried before, the first query usually fails and the second query can get the data. (Here use timer interval 0.5 seconds before the second query)

**Comment by PencilMario** [comment]
Questions need to be validated

**Comment by PencilMario** [comment]
Some people still can't check their scores after multiple mixes.

**Comment by TouchMe-Inc** [comment]
Perhaps there is such a problem, because this piece of code is not executed:
```pawn
public void SteamWorks_OnValidateClient(int iOwnerAuthId, int iAuthId)
{
	int iClient = GetClientFromSteamID(iAuthId);

	if(IS_VALID_CLIENT(iClient)) {
		SteamWorks_RequestStats(iClient, APP_L4D2); /*< HERE */
	}
}
```
Maybe I misunderstood how this function works (no docs). It says [here](https://github.com/hexa-core-eu/SteamWorks/blob/995670d04daa0ed2210e20bd8762498f23945f44/Extension/ssnatives.cpp#L71) that will return success:
```pawn 
bool bSuccess = SteamWorks_RequestStats(iClient, APP_L4D2);
if (!bSuccess) {
// Timer with next try
}
```
