### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by xiaomaolxc** [TouchMe-Inc/l4d2_mix_team#14]
Hi,
  I modified the source code named mt_capitan to meet my requirements. After the modification, I tried to compile it, but I found the following issues:

Compiling mt_capitan.sp...
SourcePawn Compiler 1.11.0.6964
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

./include/timers.inc(48) : error 418: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
./include/timers.inc(49) : error 055: start of function body without function header
./include/timers.inc(58) : error 001: expected token: ";", but found ")"
./include/timers.inc(58) : error 122: expected type expression
./include/timers.inc(58) : error 001: expected token: "-identifier-", but found "public"
./include/logging.inc(126) : error 010: invalid function or declaration
./include/logging.inc(126) : error 418: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
./include/functions.inc(360) : error 418: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
./include/functions.inc(360) : error 010: invalid function or declaration
./include/functions.inc(502) : error 418: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs
./include/functions.inc(502) : error 010: invalid function or declaration
./include/core.inc(45) : error 001: expected token: "public", but found "-identifier-"
./include/core.inc(122) : error 001: expected token: "public", but found "const"
./include/core.inc(123) : error 001: expected token: "public", but found "const"
./include/core.inc(133) : error 001: expected token: "public", but found "const"
./include/core.inc(134) : error 001: expected token: "public", but found "const"
./include/sourcemod.inc(43) : error 001: expected token: "public", but found "const"
./include/sourcemod.inc(44) : error 001: expected token: "public", but found "const"
./include/sourcemod.inc(45) : error 001: expected token: "public", but found "const"
./include/sourcemod.inc(46) : error 001: expected token: "public", but found "const"
./include/sourcemod.inc(47) : error 001: expected token: "public", but found "const"

21 Errors.

So I tried to compile the source code of the initial mt_capitan, but the same problem occurred. How should I compile it?

**Comment by TouchMe-Inc** [comment]
I would like to draw your attention to the fact that the errors refer to files that are not directly related to the plugin. Check your SourceMod. You may be trying to compile the plugin with an old version of the compiler (here old `/inclide/` ?)

**Comment by TouchMe-Inc** [comment]
Was it an online compiler?
