### ISSUE TITLE
[BUG] mt_random.sp is missing CallEndMix()

### ISSUE THREAD

**Issue by PencilMario** [TouchMe-Inc/l4d2_mix_team#3]
As the question shows, the last time I used it, the state of the team was rolled back to the state before the mix started when the game started.

https://github.com/TouchMe-Inc/l4d2_mix_team/blob/03c46c349c39ddbf69ba37b59856a97e02f08eb1/addons/sourcemod/scripting/mt_random.sp#L140-L146

**Comment by TouchMe-Inc** [comment]
Hello. Now the mix should not call CallEndMix() if it manages to complete all player movements inside OnMixInProgress. Similar bugs are possible when working with the previous version of mix_team
